!!org.myrobotlab.service.config.RuntimeConfig
enableCli: true
id: null
listeners: null
locale: null
logLevel: info
peers: null
registry:
- runtime
- security
- webgui
- intro
- python
- i01
- i01.mouth.audioFile
- i01.mouth
- i01.right
- i01.ear
- i01.rightHand.index
- i01.chatBot.search
- i01.chatBot
- i01.htmlFilter
type: Runtime
virtual: null
