!!org.myrobotlab.service.config.ProgramABConfig
autoStartPeers: true
botDir: null
bots: null
currentBotName: en-US
currentUserName: Friend
search: - i01.chatBot.search
textListeners:
- i01.htmlFilter
type: ProgramAB
utteranceListeners: [
  ]
