!!org.myrobotlab.service.config.MarySpeechConfig
audioFile: null
autoStartPeers: true
blocking: false
mute: false
speechRecognizers:
- i01.ear
- i01.head.mouthControl
substitutions: null
type: MarySpeech
voice: Mark
