!!org.myrobotlab.service.config.ProgramABConfig
autoStartPeers: true
currentBotName: en-US
currentUserName: Friend
textListeners:
- i01.htmlFilter
search: i01.chatBot.search
type: ProgramAB
utteranceListeners: [
  ]
