!!org.myrobotlab.service.config.ServoConfig
autoDisable: true
clip: true
controller: i01.right
enabled: true
idleTimeout: 3000
inverted: false
listeners: null
maxIn: 180.0
maxOut: 180.0
minIn: 0.0
minOut: 0.0
peers: null
pin: '3'
rest: 0.0
speed: 45.0
sweepMax: null
sweepMin: null
synced: null
type: Servo
