!!org.myrobotlab.service.config.InMoov2Config
analogPinFromSoundCard: 53
audioPollsBySeconds: 2
audioSignalProcessing: false
batteryInSystem: false
customSound: false
forceMicroOnIfSleeping: true
healthCheckActivated: false
healthCheckTimerMs: 60000
heartbeat: false
idleTimer: true
listeners:
- callback: onLedDisplay
  listener: i01.neoPixel
  method: publishFlash
- callback: onEvent
  listener: i01.fsm
  method: publishEvent
loadGestures: true
locale: null
neoPixelBootGreen: true
neoPixelDownloadBlue: true
neoPixelErrorRed: true
neoPixelFlashWhenSpeaking: true
openCVFaceRecognizerActivated: true
openCVFlipPicture: false
peers:
  audioPlayer:
    autoStart: true
    name: i01.audioPlayer
    type: AudioFile
  chatBot:
    autoStart: true
    name: i01.chatBot
    type: ProgramAB
  controller3:
    autoStart: false
    name: i01.controller3
    type: Arduino
  controller4:
    autoStart: false
    name: i01.controller4
    type: Arduino
  ear:
    autoStart: false
    name: i01.ear
    type: WebkitSpeechRecognition
  eyeTracking:
    autoStart: false
    name: i01.eyeTracking
    type: Tracking
  fsm:
    autoStart: false
    name: i01.fsm
    type: FiniteStateMachine
  gpt3:
    autoStart: false
    name: i01.gpt3
    type: Gpt3
  head:
    autoStart: false
    name: i01.head
    type: InMoov2Head
  headTracking:
    autoStart: false
    name: i01.headTracking
    type: Tracking
  htmlFilter:
    autoStart: true
    name: i01.htmlFilter
    type: HtmlFilter
  imageDisplay:
    autoStart: false
    name: i01.imageDisplay
    type: ImageDisplay
  leap:
    autoStart: false
    name: i01.leap
    type: LeapMotion
  left:
    autoStart: false
    name: i01.left
    type: Arduino
  leftArm:
    autoStart: false
    name: i01.leftArm
    type: InMoov2Arm
  leftHand:
    autoStart: false
    name: i01.leftHand
    type: InMoov2Hand
  mouth:
    autoStart: false
    name: i01.mouth
    type: MarySpeech
  mouthControl:
    autoStart: false
    name: i01.mouthControl
    type: MouthControl
  neoPixel:
    autoStart: false
    name: i01.neoPixel
    type: NeoPixel
  openWeatherMap:
    autoStart: false
    name: i01.openWeatherMap
    type: OpenWeatherMap
  opencv:
    autoStart: false
    name: i01.opencv
    type: OpenCV
  openni:
    autoStart: false
    name: i01.openni
    type: OpenNi
  pid:
    autoStart: false
    name: i01.pid
    type: Pid
  pir:
    autoStart: false
    name: i01.pir
    type: Pir
  random:
    autoStart: false
    name: i01.random
    type: Random
  right:
    autoStart: false
    name: i01.right
    type: Arduino
  rightArm:
    autoStart: false
    name: i01.rightArm
    type: InMoov2Arm
  rightHand:
    autoStart: false
    name: i01.rightHand
    type: InMoov2Hand
  servoMixer:
    autoStart: false
    name: i01.servoMixer
    type: ServoMixer
  simulator:
    autoStart: false
    name: i01.simulator
    type: JMonkeyEngine
  torso:
    autoStart: false
    name: i01.torso
    type: InMoov2Torso
  ultrasonicLeft:
    autoStart: false
    name: i01.ultrasonicLeft
    type: UltrasonicSensor
  ultrasonicRight:
    autoStart: false
    name: i01.ultrasonicRight
    type: UltrasonicSensor
pirEnableTracking: false
pirPlaySounds: true
pirWakeUp: true
robotCanMoveHeadWhileSpeaking: true
shutdownStartupSpeed: 50.0
sleepTimeoutMs: 300000
startBrainOnBoot: true
startMouthOnBoot: true
startupSound: true
trackingTimeoutMs: 10000
type: InMoov2
unlockInsult: forgive me
virtual: false
