!!org.myrobotlab.service.config.MouthControlConfig
delaytime: 75
delaytimeletter: 45
delaytimestop: 150
jaw: i01.head.jaw
listeners: null
mouth: i01.mouth
mouthClosedPos: 0
mouthOpenedPos: 180
neoPixel: null
peers: null
type: MouthControl
