!!org.myrobotlab.service.config.HtmlFilterConfig
listeners:
- callback: onText
  listener: i01.mouth
  method: publishText
peers: null
postHtmlTag: </pre>
preHtmlTag: <pre>
stripHtml: true
stripUrls: true
type: HtmlFilter
