!!org.myrobotlab.service.config.RuntimeConfig
enableCli: true
id: null
listeners:

locale: null
logLevel: null
peers: null
registry:
- runtime
- security
- webgui
- intro
- python
- i01
- i01.mouth.audioFile
- i01.mouth
- i01.ear
- i01.chatBot
- i01.htmlFilter
- i01.head.eyeX
- i01.head.eyeY
- i01.head.jaw
- i01.head.neck
- i01.head.rollNeck
- i01.head.rothead
- i01.head
- i01.mouthControl
- i01.opencv
- i01.right
- i01.left
type: Runtime
virtual: false
