!!org.myrobotlab.service.config.RuntimeConfig
enableCli: true
id: null
listeners: null
locale: null
logLevel: info
peers: null
registry:
- runtime
- security
- webgui
- python
- intro
- i01.audioPlayer
- i01
- i01.left
- i01.leftHand.index
- i01.leftHand.majeure
- i01.leftHand.pinky
- i01.leftHand.ringFinger
- i01.leftHand.thumb
- i01.leftHand.wrist
- i01.leftHand
- i01.mouth.audioFile
- i01.mouth
- i01.ear
- i01.htmlFilter
- i01.chatBot.search
- i01.chatBot
type: Runtime
virtual: null
