!!org.myrobotlab.service.config.ServoConfig
autoDisable: true
autoStartPeers: true
clip: true
controller: null
enabled: false
idleTimeout: 3000
inverted: false
maxIn: 180.0
maxOut: 180.0
minIn: 40.0
minOut: 40.0
pin: '9'
rest: 90.0
speed: 20.0
sweepMax: null
sweepMin: null
type: Servo
