!!org.myrobotlab.service.config.MarySpeechConfig
audioFile: null
autoStartPeers: true
blocking: false
mute: false
speechRecognizers:
- i01.head.mouthControl
- i01.mouthControl
substitutions: null
type: MarySpeech
voice: Mark
