!!org.myrobotlab.service.config.ProgramABConfig
# botDir: data/ProgramAB
botDir: ../InMoov2/resource/InMoov2/chatbot/bots/
bots:
currentBotName: en-US
currentUserName: human
listeners:
- callback: onText
  listener: i01.htmlFilter
  method: publishText
peers:
  search:
    autoStart: true
    name: i01.chatBot.search
    type: Wikipedia
sleep: false
textFilters: null
type: ProgramAB
