!!org.myrobotlab.service.config.ArduinoConfig
connect: false
listeners:
- callback: onPin
  listener: i01.pir
  method: publishPin
peers:
  serial:
    autoStart: true
    name: i01.left.serial
    type: Serial
port: null
type: Arduino
