!!org.myrobotlab.service.config.RuntimeConfig
enableCli: true
id: null
listeners:
- callback: onStopped
  listener: python
  method: stopped
- callback: onStopped
  listener: i01
  method: stopped
- callback: onStopped
  listener: i01.rightArm.bicep
  method: stopped
- callback: onStopped
  listener: i01.rightArm.omoplate
  method: stopped
- callback: onStopped
  listener: i01.rightArm.rotate
  method: stopped
- callback: onStopped
  listener: i01.rightArm.shoulder
  method: stopped
- callback: onStopped
  listener: i01.leftHand.index
  method: stopped
- callback: onStopped
  listener: i01.leftHand.majeure
  method: stopped
- callback: onStopped
  listener: i01.leftHand.pinky
  method: stopped
- callback: onStopped
  listener: i01.leftHand.ringFinger
  method: stopped
- callback: onStopped
  listener: i01.leftHand.thumb
  method: stopped
- callback: onStopped
  listener: i01.leftHand.wrist
  method: stopped
- callback: onStopped
  listener: i01.leftArm.bicep
  method: stopped
- callback: onStopped
  listener: i01.leftArm.omoplate
  method: stopped
- callback: onStopped
  listener: i01.leftArm.rotate
  method: stopped
- callback: onStopped
  listener: i01.leftArm.shoulder
  method: stopped
- callback: onStopped
  listener: i01.head.eyeX
  method: stopped
- callback: onStopped
  listener: i01.head.eyeY
  method: stopped
- callback: onStopped
  listener: i01.head.jaw
  method: stopped
- callback: onStopped
  listener: i01.head.neck
  method: stopped
- callback: onStopped
  listener: i01.head.rollNeck
  method: stopped
- callback: onStopped
  listener: i01.head.rothead
  method: stopped
- callback: onStopped
  listener: i01.rightHand.index
  method: stopped
- callback: onStopped
  listener: i01.rightHand.majeure
  method: stopped
- callback: onStopped
  listener: i01.rightHand.pinky
  method: stopped
- callback: onStopped
  listener: i01.rightHand.ringFinger
  method: stopped
- callback: onStopped
  listener: i01.rightHand.thumb
  method: stopped
- callback: onStopped
  listener: i01.rightHand.wrist
  method: stopped
- callback: onStopped
  listener: i01.torso.lowStom
  method: stopped
- callback: onStopped
  listener: i01.torso.midStom
  method: stopped
- callback: onStopped
  listener: i01.torso.topStom
  method: stopped
- callback: onCreated
  listener: python
  method: created
- callback: onCreated
  listener: i01
  method: created
- callback: onCreated
  listener: i01.rightArm.bicep
  method: created
- callback: onCreated
  listener: i01.rightArm.omoplate
  method: created
- callback: onCreated
  listener: i01.rightArm.rotate
  method: created
- callback: onCreated
  listener: i01.rightArm.shoulder
  method: created
- callback: onCreated
  listener: i01.leftHand.index
  method: created
- callback: onCreated
  listener: i01.leftHand.majeure
  method: created
- callback: onCreated
  listener: i01.leftHand.pinky
  method: created
- callback: onCreated
  listener: i01.leftHand.ringFinger
  method: created
- callback: onCreated
  listener: i01.leftHand.thumb
  method: created
- callback: onCreated
  listener: i01.leftHand.wrist
  method: created
- callback: onCreated
  listener: i01.leftArm.bicep
  method: created
- callback: onCreated
  listener: i01.leftArm.omoplate
  method: created
- callback: onCreated
  listener: i01.leftArm.rotate
  method: created
- callback: onCreated
  listener: i01.leftArm.shoulder
  method: created
- callback: onCreated
  listener: i01.head.eyeX
  method: created
- callback: onCreated
  listener: i01.head.eyeY
  method: created
- callback: onCreated
  listener: i01.head.jaw
  method: created
- callback: onCreated
  listener: i01.head.neck
  method: created
- callback: onCreated
  listener: i01.head.rollNeck
  method: created
- callback: onCreated
  listener: i01.head.rothead
  method: created
- callback: onCreated
  listener: i01.rightHand.index
  method: created
- callback: onCreated
  listener: i01.rightHand.majeure
  method: created
- callback: onCreated
  listener: i01.rightHand.pinky
  method: created
- callback: onCreated
  listener: i01.rightHand.ringFinger
  method: created
- callback: onCreated
  listener: i01.rightHand.thumb
  method: created
- callback: onCreated
  listener: i01.rightHand.wrist
  method: created
- callback: onCreated
  listener: i01.torso.lowStom
  method: created
- callback: onCreated
  listener: i01.torso.midStom
  method: created
- callback: onCreated
  listener: i01.torso.topStom
  method: created
- callback: onRegistered
  listener: webgui
  method: registered
- callback: onRegistered
  listener: python
  method: registered
- callback: registered
  listener: intro
  method: registered
- callback: onRegistered
  listener: i01
  method: registered
- callback: onRegistered
  listener: i01.rightArm.bicep
  method: registered
- callback: onRegistered
  listener: i01.rightArm.omoplate
  method: registered
- callback: onRegistered
  listener: i01.rightArm.rotate
  method: registered
- callback: onRegistered
  listener: i01.rightArm.shoulder
  method: registered
- callback: onRegistered
  listener: i01.leftHand.index
  method: registered
- callback: onRegistered
  listener: i01.leftHand.majeure
  method: registered
- callback: onRegistered
  listener: i01.leftHand.pinky
  method: registered
- callback: onRegistered
  listener: i01.leftHand.ringFinger
  method: registered
- callback: onRegistered
  listener: i01.leftHand.thumb
  method: registered
- callback: onRegistered
  listener: i01.leftHand.wrist
  method: registered
- callback: onRegistered
  listener: i01.leftArm.bicep
  method: registered
- callback: onRegistered
  listener: i01.leftArm.omoplate
  method: registered
- callback: onRegistered
  listener: i01.leftArm.rotate
  method: registered
- callback: onRegistered
  listener: i01.leftArm.shoulder
  method: registered
- callback: onRegistered
  listener: i01.head.eyeX
  method: registered
- callback: onRegistered
  listener: i01.head.eyeY
  method: registered
- callback: onRegistered
  listener: i01.head.jaw
  method: registered
- callback: onRegistered
  listener: i01.head.neck
  method: registered
- callback: onRegistered
  listener: i01.head.rollNeck
  method: registered
- callback: onRegistered
  listener: i01.head.rothead
  method: registered
- callback: onRegistered
  listener: i01.rightHand.index
  method: registered
- callback: onRegistered
  listener: i01.rightHand.majeure
  method: registered
- callback: onRegistered
  listener: i01.rightHand.pinky
  method: registered
- callback: onRegistered
  listener: i01.rightHand.ringFinger
  method: registered
- callback: onRegistered
  listener: i01.rightHand.thumb
  method: registered
- callback: onRegistered
  listener: i01.rightHand.wrist
  method: registered
- callback: onRegistered
  listener: i01.simulator
  method: registered
- callback: onRegistered
  listener: i01.torso.lowStom
  method: registered
- callback: onRegistered
  listener: i01.torso.midStom
  method: registered
- callback: onRegistered
  listener: i01.torso.topStom
  method: registered
- callback: onStarted
  listener: python
  method: started
- callback: onStarted
  listener: i01
  method: started
- callback: onStarted
  listener: i01.rightArm.bicep
  method: started
- callback: onStarted
  listener: i01.rightArm.omoplate
  method: started
- callback: onStarted
  listener: i01.rightArm.rotate
  method: started
- callback: onStarted
  listener: i01.rightArm.shoulder
  method: started
- callback: onStarted
  listener: i01.leftHand.index
  method: started
- callback: onStarted
  listener: i01.leftHand.majeure
  method: started
- callback: onStarted
  listener: i01.leftHand.pinky
  method: started
- callback: onStarted
  listener: i01.leftHand.ringFinger
  method: started
- callback: onStarted
  listener: i01.leftHand.thumb
  method: started
- callback: onStarted
  listener: i01.leftHand.wrist
  method: started
- callback: onStarted
  listener: i01.leftArm.bicep
  method: started
- callback: onStarted
  listener: i01.leftArm.omoplate
  method: started
- callback: onStarted
  listener: i01.leftArm.rotate
  method: started
- callback: onStarted
  listener: i01.leftArm.shoulder
  method: started
- callback: onStarted
  listener: i01.head.eyeX
  method: started
- callback: onStarted
  listener: i01.head.eyeY
  method: started
- callback: onStarted
  listener: i01.head.jaw
  method: started
- callback: onStarted
  listener: i01.head.neck
  method: started
- callback: onStarted
  listener: i01.head.rollNeck
  method: started
- callback: onStarted
  listener: i01.head.rothead
  method: started
- callback: onStarted
  listener: i01.rightHand.index
  method: started
- callback: onStarted
  listener: i01.rightHand.majeure
  method: started
- callback: onStarted
  listener: i01.rightHand.pinky
  method: started
- callback: onStarted
  listener: i01.rightHand.ringFinger
  method: started
- callback: onStarted
  listener: i01.rightHand.thumb
  method: started
- callback: onStarted
  listener: i01.rightHand.wrist
  method: started
- callback: onStarted
  listener: i01.torso.lowStom
  method: started
- callback: onStarted
  listener: i01.torso.midStom
  method: started
- callback: onStarted
  listener: i01.torso.topStom
  method: started
- callback: onConfigList
  listener: i01
  method: publishConfigList
- callback: onFinishedConfig
  listener: i01
  method: publishFinishedConfig
- callback: onReleased
  listener: webgui
  method: released
- callback: onReleased
  listener: python
  method: released
- callback: released
  listener: intro
  method: released
- callback: onReleased
  listener: i01
  method: released
- callback: onReleased
  listener: i01.rightArm.bicep
  method: released
- callback: onReleased
  listener: i01.rightArm.omoplate
  method: released
- callback: onReleased
  listener: i01.rightArm.rotate
  method: released
- callback: onReleased
  listener: i01.rightArm.shoulder
  method: released
- callback: onReleased
  listener: i01.leftHand.index
  method: released
- callback: onReleased
  listener: i01.leftHand.majeure
  method: released
- callback: onReleased
  listener: i01.leftHand.pinky
  method: released
- callback: onReleased
  listener: i01.leftHand.ringFinger
  method: released
- callback: onReleased
  listener: i01.leftHand.thumb
  method: released
- callback: onReleased
  listener: i01.leftHand.wrist
  method: released
- callback: onReleased
  listener: i01.leftArm.bicep
  method: released
- callback: onReleased
  listener: i01.leftArm.omoplate
  method: released
- callback: onReleased
  listener: i01.leftArm.rotate
  method: released
- callback: onReleased
  listener: i01.leftArm.shoulder
  method: released
- callback: onReleased
  listener: i01.head.eyeX
  method: released
- callback: onReleased
  listener: i01.head.eyeY
  method: released
- callback: onReleased
  listener: i01.head.jaw
  method: released
- callback: onReleased
  listener: i01.head.neck
  method: released
- callback: onReleased
  listener: i01.head.rollNeck
  method: released
- callback: onReleased
  listener: i01.head.rothead
  method: released
- callback: onReleased
  listener: i01.rightHand.index
  method: released
- callback: onReleased
  listener: i01.rightHand.majeure
  method: released
- callback: onReleased
  listener: i01.rightHand.pinky
  method: released
- callback: onReleased
  listener: i01.rightHand.ringFinger
  method: released
- callback: onReleased
  listener: i01.rightHand.thumb
  method: released
- callback: onReleased
  listener: i01.rightHand.wrist
  method: released
- callback: onReleased
  listener: i01.torso.lowStom
  method: released
- callback: onReleased
  listener: i01.torso.midStom
  method: released
- callback: onReleased
  listener: i01.torso.topStom
  method: released
- callback: onShutdown
  listener: i01
  method: shutdown
locale: null
logLevel: null
peers: null
registry:
- runtime
- security
- webgui
- python
- intro
- i01.audioPlayer
- i01
- i01.chatBot.search
- i01.chatBot
- i01.ear
- i01.left.serial
- i01.left
- i01.right.serial
- i01.right
- i01.rightArm.bicep
- i01.rightArm.omoplate
- i01.rightArm.rotate
- i01.rightArm.shoulder
- i01.rightArm
- i01.leftHand.index
- i01.leftHand.majeure
- i01.leftHand.pinky
- i01.leftHand.ringFinger
- i01.leftHand.thumb
- i01.leftHand.wrist
- i01.leftHand
- i01.leftArm.bicep
- i01.leftArm.omoplate
- i01.leftArm.rotate
- i01.leftArm.shoulder
- i01.leftArm
- i01.htmlFilter
- i01.head.eyeX
- i01.head.eyeY
- i01.head.jaw
- i01.head.neck
- i01.head.rollNeck
- i01.head.rothead
- i01.head
- i01.mouth.audioFile
- i01.mouth
- i01.mouthControl
- i01.neoPixel
- i01.opencv
- i01.rightHand.index
- i01.rightHand.majeure
- i01.rightHand.pinky
- i01.rightHand.ringFinger
- i01.rightHand.thumb
- i01.rightHand.wrist
- i01.rightHand
- i01.simulator
- i01.torso.lowStom
- i01.torso.midStom
- i01.torso.topStom
- i01.torso
- i01.ultrasonicLeft
- i01.ultrasonicRight
- i01.imageDisplay
type: Runtime
virtual: null
