!!org.myrobotlab.service.config.OpenCVConfig
cameraIndex: 0
capturing: false
filters: {
  }
flip: false  
grabberType: OpenCV
inputFile: null
inputSource: camera
listeners: null
nativeViewer: true
peers: null
type: OpenCV
webViewer: false
