!!org.myrobotlab.service.config.NeoPixelConfig
autoClear: false
blue: 212
brightness: 255
controller: null
currentAnimation: Ironman
fill: false
green: 180
idleTimeout: 1000
listeners: null
peers: null
pin: 2
pixelCount: 16
pixelDepth: 3
red: 12
speed: 10
type: NeoPixel
