!!org.myrobotlab.service.config.OpenCVConfig
cameraIndex: 0
capturing: false
filters: {
  }
grabberType: OpenCV
inputFile: null
inputSource: camera
listeners:
- callback: onCvData
  listener: i01.simulator
  method: publishCvData
nativeViewer: true
peers: null
type: OpenCV
webViewer: false
