!!org.myrobotlab.service.config.NeoPixelConfig
audioAnimation: Ironman
blue: 212
brightness: 255
controller: i01.controller3
currentAnimation: Ironman
fill: false
flashMap:
  warn:
  - !!org.myrobotlab.service.config.NeoPixelConfig$Flash
    blue: 0
    green: 100
    red: 100
    timeOff: 30
    timeOn: 30
    white: 0
  - !!org.myrobotlab.service.config.NeoPixelConfig$Flash
    blue: 0
    green: 100
    red: 100
    timeOff: 30
    timeOn: 30
    white: 0
  - !!org.myrobotlab.service.config.NeoPixelConfig$Flash
    blue: 0
    green: 100
    red: 100
    timeOff: 30
    timeOn: 30
    white: 0
  speaking:
  - !!org.myrobotlab.service.config.NeoPixelConfig$Flash
    blue: 90
    green: 183
    red: 0
    timeOff: 30
    timeOn: 60
    white: 0
  - !!org.myrobotlab.service.config.NeoPixelConfig$Flash
    blue: 90
    green: 183
    red: 0
    timeOff: 30
    timeOn: 60
    white: 0
  heartbeat:
  - !!org.myrobotlab.service.config.NeoPixelConfig$Flash
    blue: 0
    green: 110
    red: 210
    timeOff: 30
    timeOn: 100
    white: 0
  - !!org.myrobotlab.service.config.NeoPixelConfig$Flash
    blue: 0
    green: 110
    red: 210
    timeOff: 30
    timeOn: 100
    white: 0
  success:
  - !!org.myrobotlab.service.config.NeoPixelConfig$Flash
    blue: 120
    green: 0
    red: 0
    timeOff: 30
    timeOn: 30
    white: 0
  pir:
  - !!org.myrobotlab.service.config.NeoPixelConfig$Flash
    blue: 90
    green: 200
    red: 60
    timeOff: 30
    timeOn: 30
    white: 0
  - !!org.myrobotlab.service.config.NeoPixelConfig$Flash
    blue: 90
    green: 200
    red: 60
    timeOff: 30
    timeOn: 30
    white: 0
  - !!org.myrobotlab.service.config.NeoPixelConfig$Flash
    blue: 90
    green: 200
    red: 60
    timeOff: 30
    timeOn: 30
    white: 0
  error:
  - !!org.myrobotlab.service.config.NeoPixelConfig$Flash
    blue: 0
    green: 0
    red: 120
    timeOff: 30
    timeOn: 30
    white: 0
  - !!org.myrobotlab.service.config.NeoPixelConfig$Flash
    blue: 0
    green: 0
    red: 120
    timeOff: 30
    timeOn: 30
    white: 0
  - !!org.myrobotlab.service.config.NeoPixelConfig$Flash
    blue: 0
    green: 0
    red: 120
    timeOff: 30
    timeOn: 30
    white: 0
  info:
  - !!org.myrobotlab.service.config.NeoPixelConfig$Flash
    blue: 0
    green: 0
    red: 120
    timeOff: 30
    timeOn: 30
    white: 0
green: 180
listeners: null
peers: null
pin: 2
pixelCount: 16
pixelDepth: 3
red: 12
speed: 10
type: NeoPixel
