!!org.myrobotlab.service.config.RuntimeConfig
enableCli: true
id: null
listeners: null
locale: null
logLevel: info
peers: null
registry:
- runtime
- security
- webgui
- python
- intro
- i01.audioPlayer
- i01
- i01.htmlFilter
- i01.chatBot.search
- i01.chatBot
- i01.ear
- i01.left.serial
- i01.left
- i01.right.serial
- i01.right
- i01.rightArm.bicep
- i01.rightArm.omoplate
- i01.rightArm.rotate
- i01.rightArm.shoulder
- i01.rightArm
- i01.leftHand.index
- i01.leftHand.majeure
- i01.leftHand.pinky
- i01.leftHand.ringFinger
- i01.leftHand.thumb
- i01.leftHand.wrist
- i01.leftHand
- i01.leftArm.bicep
- i01.leftArm.omoplate
- i01.leftArm.rotate
- i01.leftArm.shoulder
- i01.leftArm
- i01.head.eyeX
- i01.head.eyeY
- i01.head.jaw
- i01.head.neck
- i01.head.rollNeck
- i01.head.rothead
- i01.head
- i01.mouth.audioFile
- i01.mouth
- i01.mouthControl
- i01.neoPixel
- i01.opencv
- i01.rightHand.index
- i01.rightHand.majeure
- i01.rightHand.pinky
- i01.rightHand.ringFinger
- i01.rightHand.thumb
- i01.rightHand.wrist
- i01.rightHand
- i01.simulator
- i01.torso.lowStom
- i01.torso.midStom
- i01.torso.topStom
- i01.torso
- i01.ultrasonicLeft
- i01.ultrasonicRight
- i01.imageDisplay
type: Runtime
virtual: false
