def printList():
    gesturesList = ["CLOSE YOUR FINGER", "OPEN YOUR FINGER", "FINGER TO THE MIDDLE", 
        "ACTION YOUR FINGER", "OPEN HAND", "CLOSE HAND", "OPEN HANDS", 
        "CLOSE HANDS", "OPEN YOUR RIGHT HAND", "OPEN YOUR LEFT HAND", 
        "CLOSE YOUR RIGHT HAND", "CLOSE YOUR LEFT HAND", 
        "SLOWLY CLOSE YOUR RIGHT HAND""CAMERA ON", "OFF CAMERA", "SEARCH HUMANS", 
        "FACE DETECTION", "LOOK AT ME", "QUIT SEARCH", "TRACK", "FREEZE TRACK", 
        "STOP YOUR TRACKING", "TAKE A PICTURE", "CAPTURE GESTURE", "PLAY MUSIC", "STOP MUSIC",
        "REST", "GIVING", "FIGHTER", "FIST HIPS", "LOOK AT THIS", "VICTORY", 
        "ARMS UP", "ARMS FRONT", "DA VINCI", "STOP LISTENING", "VOICE CONTROL", 
        "FULL SPEED", "HALF SPEED", "PICTURE ON THE RIGHT SIDE", 
        "PICTURE ON THE LEFT SIDE", "PICTURE ON BOTH SIDES", "LOOK ON YOUR RIGHT SIDE", 
        "LOOK ON YOUR LEFT SIDE", "LOOK IN THE MIDDLE", "LOOK UP", "LOOK DOWN", 
        "TILT YOUR HEAD ON THE RIGHT SIDE", "TILT YOUR HEAD ON THE LEFT SIDE", 
        "SHAKE HAND", "WHAT DO YOU SEE"
        ]
    for i in gesturesList:
        print(i)
