!!org.myrobotlab.service.config.ServoConfig
autoDisable: true
clip: true
controller: i01.left
enabled: false
idleTimeout: 3000
inverted: false
maxIn: 90.0
maxOut: 90.0
minIn: 5.0
minOut: 5.0
pin: '8'
rest: 5.0
speed: 20.0
sweepMax: null
sweepMin: null
synced: null
type: Servo
