!!org.myrobotlab.service.config.ServoConfig
autoDisable: true
clip: true
controller: i01.left
enabled: false
idleTimeout: 3000
inverted: false
maxIn: 120.0
maxOut: 120.0
minIn: 60.0
minOut: 60.0
peers: null
pin: '27'
rest: 90.0
speed: 5.0
sweepMax: null
sweepMin: null
synced: null
type: Servo
