!!org.myrobotlab.service.config.ServoConfig
autoDisable: true
clip: true
controller: i01.left
enabled: true
idleTimeout: 3000
inverted: false
listeners: null
maxIn: 90.0
maxOut: 90.0
minIn: 0.0
minOut: 0.0
peers: null
pin: '8'
rest: 0.0
speed: 45.0
sweepMax: null
sweepMin: null
synced: null
type: Servo
