!!org.myrobotlab.service.config.ServoConfig
autoDisable: true
clip: true
controller: i01.left
enabled: false
idleTimeout: 3000
inverted: false
maxIn: 150.0
maxOut: 150.0
minIn: 30.0
minOut: 30.0
peers: null
pin: '13'
rest: 90.0
speed: 45.0
sweepMax: null
sweepMin: null
synced: null
type: Servo
