!!org.myrobotlab.service.config.WebkitSpeechRecognitionConfig
afterSpeakingPauseMs: 2000
listeners:
- callback: onText
  listener: i01.chatBot
  method: publishText
listening: true
peers: null
recording: false
textListeners:
- i01.chatBot
type: WebkitSpeechRecognition
wakeWord: null
wakeWordIdleTimeoutSeconds: 10
