def darkSide():
  fullspeed()
  if runtime.isStarted('i01.neoPixel'):
    i01_neoPixel.setAnimation("Color Wipe", 200, 0, 0, 50)
    i01_head.moveTo(0, 90)
    forheadsU()
    eyelidsHalfShut()
    upperLipU()
    cheeksD()
    browsD()
    handsclose()
    i01_audioPlayer.playFile('resource/InMoov2/system/sounds/Darth Vader Breathing.mp3')
    sleep(12)
    relax()
    neutral()
  else:
    i01_head.moveTo(0, 90)
    forheadsU()
    eyelidsHalfShut()
    upperLipU()
    cheeksD()
    browsD()
    handsclose()
    i01_audioPlayer.playFileBlocking('resource/InMoov2/system/sounds/Darth Vader Breathing.mp3')
    sleep(12)
    relax()
    neutral()
