def printList_EN():
    gesturesList = ["CLOSE YOUR FINGER", "OPEN YOUR FINGER", "FINGER TO THE MIDDLE", 
        "ACTION YOUR FINGER", "OPEN HAND", "CLOSE HAND", "OPEN HANDS", 
        "CLOSE HANDS", "OPEN YOUR RIGHT HAND", "OPEN YOUR LEFT HAND", 
        "CLOSE YOUR RIGHT HAND", "CLOSE YOUR LEFT HAND", 
        "SLOWLY CLOSE YOUR RIGHT HAND", "CAMERA ON", "OFF CAMERA", "SEARCH HUMANS", 
        "FACE DETECTION", "LOOK AT ME", "QUIT SEARCH", "TRACK", "FREEZE TRACK", 
        "STOP YOUR TRACKING", "TAKE A PICTURE", "CAPTURE GESTURE", "PLAY MUSIC", "STOP MUSIC",
        "REST", "GIVING", "FIGHTER", "FIST HIPS", "LOOK AT THIS", "VICTORY", 
        "ARMS UP", "ARMS FRONT", "DA VINCI", "MOVEMENT NUMBER 3", "STOP LISTENING", "VOICE CONTROL", 
        "FULL SPEED", "HALF SPEED", "PICTURE ON THE RIGHT SIDE", 
        "PICTURE ON THE LEFT SIDE", "PICTURE ON BOTH SIDES", "LOOK ON YOUR RIGHT SIDE", 
        "LOOK ON YOUR LEFT SIDE", "LOOK IN THE MIDDLE", "LOOK UP", "LOOK DOWN", 
        "TILT YOUR HEAD ON THE RIGHT SIDE", "TILT YOUR HEAD ON THE LEFT SIDE", 
        "SHAKE HAND", "WHAT DO YOU SEE", "PLAY MUSIC", "STOP MUSIC", "PLAY NEXT SONG", "PLAY RANDOM MUSIC",
        "SEARCH YOUTUBE *","EXECUTE *","SWITCH TO FRENCH"
        ]
    for i in gesturesList:
        print(i)

def printList_FR():
    gesturesList = ["FERME TON DOIGT", "OUVRE TON DOIGT", "DOIGT AU MILIEU", "OUVRE TES MAINS", 
        "FERME TES MAINS", "OUVRE TA MAIN DROITE", "OUVRE TA MAIN GAUCHE",
        "FERME TA MAIN DROITE", "FERME TA MAIN GAUCHE", "DOUCEMENT FERME TA MAIN DROITE", 
        "DOUCEMENT FERME TA MAIN GAUCHE", "DÉMARRE LA CAMÉRA", "ARRÊTE LA CAMÉRA", "RECHERCHE HUMAINS",
        "APPRENTISSAGE DE VISAGE", "RECONNAISSANCE FACIALE", "ARRÊTE LA RECONNAISSANCE FACIALE",
        "ARRÊTER VOTRE SUIVI", "PRENDRE UNE PHOTO", "CAPTURE LES GESTUELLES", "DÉMARRE LA PLAYLIST", "ARRÊTE LA PLAYLIST",
        "RESTE", "DONNE", "RELAX", "BAGARREUR", "MAINS SUR LES HANCHES", "REGARDE CECI", "VICTOIRE",
        "BRAS EN L AIR", "BRAS EN AVANT", "DA VINCI", "MANUEL", "COMMANDE VOCALE",
        "VITESSE MAXI", "PHOTO À DROITE",
        "PHOTO À GAUCHE", "PHOTO DES DEUX COTÉS", "REGARDE SUR TA DROITE",
        "REGARDE SUR TA GAUCHE", "REGARDE AU MILIEU", "REGARDE EN HAUT", "REGARDE EN BAS",
        "PENCHE LA TÊTE À DROITE", "PENCHE LA TÊTE À GAUCHE",
        "SERRE LA MAIN", "QUE VOIS TU", "ENVOYER UN EMAIL A *", "LIRE LES MAILS DE *", "LIRE LES MESSAGES DE *"
        ]
    for i in gesturesList:
        print unicode(i,'utf-8')

def printList_ES():
    gesturesList = ["CIERRE SU DEDO", "ABRE TU DEDO", "DEDO AL MEDIO", "MANOS ABIERTAS", 
        "CIERRE LAS MANOS", "ABRE TU MANO DERECHA", "ABRE TU MANO IZQUIERDA",
        "CIERRA TU MANO DERECHA", "CIERRA TU MANO IZQUIERDA", "CIERRE LENTAMENTE SU MANO DERECHA", 
        "CIERRE LENTAMENTE SU MANO IZQUIERDA", "CÁMARA ENCENDIDA", "CÁMARA APAGADA",
        "INICIAR RECONOCEDOR DE CARA", "BUSCAR HUMANOS", "SALIR DE BÚSQUEDA",
        "STOP RECONOCEDOR DE CARA", "FOTO", "GESTO DE CAPTURA", "EMPIEZA A TOCAR MÚSICA", "DEJAR DE TOCAR MÚSICA",
        "DESCANSO", "DANDO", "RELAJARSE", "COMBATIENTE", "PUÑO DE CADERAS", "MIRA ESTO", "VICTORIA",
        "BRAZOS ARRIBA", "BRAZOS AL FRENT", "DA VINCI",
        "A TODA VELOCIDAD", "IMAGEN DEL LADO DERECHO",
        "IMAGEN DEL LADO IZQUIERDO", "IMAGEN EN AMBOS LADOS", "MIRA A TU LADO DERECHO",
        "MIRA A TU LADO IZQUIERDO", "MIRA EN EL MEDIO", "MIRAR PARA ARRIBA", "MIRA ABAJO",
        "INCLINA LA CABEZA HACIA EL LADO DERECHO", "INCLINA TU CABEZA HACIA EL LADO IZQUIERDO",
        "ESTRECHAR LA MANO", "QUÉ VES", "CÓMO TE SIENTES"
        ]
    for i in gesturesList:
        print unicode(i,'utf-8')

def printList_DE():
    gesturesList = ["SCHLIESSEN SIE IHREN FINGER", "ÖFFNEN SIE IHREN FINGER", "FINGER IN DIE MITTE",
        "HANDELN SIE IHREN FINGER", "ÖFFNEN SIE IHRE HAND", "SCHLIESSEN SIE IHRE HAND", "HÄNDE ÖFFNEN",
        "HÄNDE SCHLIESSEN", "ÖFFNEN SIE IHRE RECHTE HAND", "ÖFFNEN SIE IHRE LINKE HAND",
        "SCHLIESSEN SIE IHRE RECHTE HAND", "SCHLIESSEN SIE IHRE LINKE HAND",
        "SCHLIESSEN SIE LANGSAM IHRE RECHTE HAND", "KAMERA AN", "KAMERA AUS", "SUCHEN MENSCHEN",
        "GESICHTSERKENNUNG", "SCHAU MICH AN", "BEENDEN SIE DIE SUCHE", "SPUR", "STOPPEN SIE IHRE SPUR",
        "MACHEN SIE EIN BILD", "GESTE AUFNEHMEN", "MUSIK ABSPIELEN", "MUSIK STOPPEN",
        "REST", "GEBEN", "KÄMPFER", "FAUSTHÜFTEN", "SCHAU DIR DAS AN", "SIEG",
        "ARME NACH OBEN", "ARME VORNE", "DA VINCI", "HÖR AUF ZUZUHÖREN", "SPRACHSTEUERUNG",
        "VOLLGAS", "HALBGESCHWINDIGKEIT", "BILD AUF DER RECHTEN SEITE",
        "BILD AUF DER LINKEN SEITE", "BILD AUF BEIDEN SEITEN", "SCHAUEN SIE AUF IHRE RECHTE SEITE",
        "SCHAUEN SIE NACH DER LINKEN SEITE", "SCHAUEN SIE IN DIE MITTE", "SCHAUEN SIE NACH OBEN", "SCHAUEN SIE NACH UNTEN",
        "NEIGE DEINEN KOPF AUF DER RECHTEN SEITE", "NEIGE DEINEN KOPF AUF DER LINKEN SEITE",
        "HAND SCHÜTTELN", "WAS SIEHST DU"]
    for i in gesturesList:
        print unicode(i,'utf-8')

def printList_PL():
    gesturesList = ["ZAMKNIJ PALEC", "OTWÓRZ PALEC", "PALEC DO ŚRODKA", 
        "DZIAŁAJ PALCEM", "OTWARTA DŁOŃ", "ZAMKNIJ RĘKĘ", "OTWARTE DŁONIE", 
        "ZAMKNIJ RĘCE", "OTWÓRZ SWOJĄ PRAWĄ RĘKĘ", "OTWÓRZ LEWĄ RĘKĘ", 
        "ZAMKNIJ PRAWĄ RĘKĘ", "ZAMKNIJ LEWĄ RĘKĘ", 
        "WOLNO ZAMKNIJ PRAWĄ RĘKĘ", "KAMERA WŁĄCZONA", "WYŁĄCZ KAMERA", "SZUKAJ LUDZI", 
        "WYKRYWANIE TWARZY", "SPÓJRZ NA MNIE", "ZAKOŃCZ WYSZUKIWANIE", "ŚCIEŻKA", "ZAMRAŻ UTWÓR", 
        "ZATRZYMAJ ŚLEDZENIE", "ZROBIĆ ZDJĘCIE", "UCHWYĆ GEST", "GRAJ MUZYKĘ", "ZATRZYMAJ MUZYKĘ",
        "RESZTA", "DAJĄCY", "WOJOWNIK", "PIĘŚCI BIODRA", "SPÓJRZ NA TO", "ZWYCIĘSTWO", 
        "RAMIONA DO GÓRY", "RAMIONA PRZÓD", "DA VINCI", "RUCH NUMER 3", "PRZESTAŃ SŁUCHAĆ", "KONTROLA GŁOSU", 
        "PEŁNA PRĘDKOŚĆ", "PÓŁ PRĘDKOŚCI", "OBRAZEK PO PRAWEJ STRANIE", 
        "OBRAZ PO LEWEJ STRANIE", "ZDJĘCIE PO OBU STRONACH", "SPÓJRZ NA SWOJĄ PRAWĄ STRONĘ", 
        "SPÓJRZ NA LEWĄ STRONĘ", "PATRZ W ŚRODEK", "SPOJRZEĆ W GÓRĘ", "SPÓJRZ W DÓŁ", 
        "PRZECHYL GŁOWĘ NA PRAWĄ BRONĘ", "PRZECHYL GŁOWĘ NA LEWĄ BRONĘ", 
        "UŚCISK RĘKI", "CO WIDZISZ", "ODTWÓRZ NASTĘPNĄ PIOSENKĘ", "ODTWÓRZ LOSOWĄ MUZYKĘ",
        "SZUKAJ W YOUTUBE *","WYKONAĆ *","PRZEJDŹ NA POLSKI", "PRZEŁĄCZ NA ANGIELSKI"
        ]
    for i in gesturesList:
        print unicode(i,'utf-8')        
